//For login
export const LOGIN_LOADING="LOGIN LOADING";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_ERROR="LOGIN_ERROR";

//For Signup
export const SIGNUP_LOADING="SIGNUP_LOADING";
export const SIGNUP_SUCCESS="SIGNUP_SUCCESS";
export const SIGNUP_ERROR="SIGNUP_ERROR";

//For Profile Fetch
export const PROFILE_LOADING="PROFILE_LOADING";
export const PROFILE_SUCCESS="PROFILE_SUCCESS";
export const PROFILE_ERROR="PROFILE_ERROR";